apiVersion: v1
kind: Service
metadata:
  name: dvldb-host-path-mount-container-service-c8875b5b
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: host-path-mount-container
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvldb-host-path-mount-container-deployment-c8ad4fcb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: host-path-mount-container
  template:
    metadata:
      labels:
        app: host-path-mount-container
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /mounted/
              name: host-mounted
      volumes:
        - hostPath:
            path: /var/log/
          name: host-mounted
