apiVersion: v1
kind: Service
metadata:
  name: dvldb-privileged-container-service-c800b550
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: dvldb-privileged-container
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvldb-privileged-container-deployment-c878e6e7
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dvldb-privileged-container
  template:
    metadata:
      labels:
        app: dvldb-privileged-container
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
