apiVersion: v1
kind: ServiceAccount
metadata:
  name: dvldb-cluster-admin-dvldbadminserviceaccount-c8c75bc6
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dvldb-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: dvldb-cluster-admin-dvldbadminserviceaccount-c8c75bc6
    namespace: default
