apiVersion: v1
kind: Service
metadata:
  name: dvldb-cap-sys-admin-container-service-c80f13d2
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: cap-sys-admin-container
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvldb-cap-sys-admin-container-deployment-c80ea643
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cap-sys-admin-container
  template:
    metadata:
      labels:
        app: cap-sys-admin-container
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 8080
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
