apiVersion: v1
kind: Service
metadata:
  name: dvldb-host-pid-container-service-c8f7b7d9
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: host-pid-container
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvldb-host-pid-container-deployment-c8a444cd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: host-pid-container
  template:
    metadata:
      labels:
        app: host-pid-container
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 8080
      hostPID: true
