Resources:
  SqsPublicQueueQueue1F58A71E:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: SqsPublicQueueStack/SqsPublicQueueQueue/Resource
  SqsPublicQueueQueuePolicy928E815C:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sqs:ReceiveMessage
            Effect: Allow
            Principal: "*"
            Resource:
              Fn::GetAtt:
                - SqsPublicQueueQueue1F58A71E
                - Arn
        Version: "2012-10-17"
      Queues:
        - Ref: SqsPublicQueueQueue1F58A71E
    Metadata:
      aws:cdk:path: SqsPublicQueueStack/SqsPublicQueueQueue/Policy/Resource
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
