name: dvldb-cdk

on:
  push:
    branches:
      - master
      - test-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: cd k8s/privileged-container && npm install && npm run test
      - run: cd k8s/root-user-container && npm install && npm run test
      - run: cd k8s/cluster-admin-used && npm install && npm run test
