name: dvldb-cdk

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd k8s/privileged-container/typescript/ && npm install && npm run test
      - run: cd k8s/root-user-container/typescript/ && npm install && npm run test
      - run: cd k8s/cluster-admin-used/typescript/ && npm install && npm run test
      - run: cd aws/s3-public-bucket/ && npm install && npm run test
      - run: cd aws/iam-admin-role/ && npm install && npm run test
      - run: cd aws/sqs-public-queue/ && npm install && npm run test
