name: dvldb-cdk

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd k8s/privileged-container/typescript/ && npm install && npm run test
      - run: cd k8s/root-user-container/typescript/ && npm install && npm run test
      - run: cd k8s/cluster-admin-used/typescript/ && npm install && npm run test
      - run: cd k8s/sys-admin-cap-container/typescript/ && npm install && npm run test
      - run: cd k8s/host-path-mount-container/typescript/ && npm install && npm run test
      - run: cd k8s/host-pid-container/typescript/ && npm install && npm run test
      - run: cd k8s/log4shell-container/typescript/ && npm install && npm run test
      - run: cd k8s/sensitive-read/typescript/ && npm install && npm run test
      - run: cd aws/s3-public-bucket/typescript/ && npm install && npm run test
      - run: cd aws/iam-admin-role/typescript/ && npm install && npm run test
      - run: cd aws/sqs-public-queue/typescript/ && npm install && npm run test
